name: Release new version

on:
  workflow_run:
    workflows: ['Validate OpenAPI']
    branches: [main]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Create Tag
        run: |
          VERSION=$(<VERSION)
          TAG_NAME="v$VERSION"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a $TAG_NAME -m "$TAG_NAME"
          git push origin $TAG_NAME
      - name: Generate CHANGELOG data
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ env.TAG_NAME }}
          includeRefIssues: false
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ env.TAG_NAME }}
          body: ${{ steps.changelog.outputs.changes }}
          tag: ${{ env.TAG_NAME }}
          token: ${{ github.token }}
