name: OpenAPI Validator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
      - uses: pnpm/action-setup@v3
      - name: Validate OpenAPI specs
        run: |
          if git diff --quiet origin/main -- openapi/; then
            echo "No OpenAPI spec changes detected. Exiting."
            exit 0
          fi

          echo "Installing dependencies..."
          pnpm install --frozen-lockfile

          echo "Running OpenAPI lint..."
          pnpm lint:openapi
